// Optional end-to-end check: PLAYWRIGHT_MODULE can point to an existing Playwright installation.
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const baseURL = process.env.TEST_URL || 'http://localhost:5188';
const output = path.join(__dirname,'..','test-results');
fs.mkdirSync(output,{recursive:true});
(async () => {
  const browser = await chromium.launch({channel:'chrome',headless:true});
  try {
    const context = await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,timezoneId:'Asia/Shanghai',acceptDownloads:true});
    const page = await context.newPage();
    const errors = []; page.on('pageerror',error => errors.push(error.message));
    await page.clock.install({time:new Date('2026-10-04T03:00:00Z')});
    await page.goto(baseURL);
    await page.locator('.task-row').first().waitFor();
    assert.equal(await page.locator('.task-row').count(),6);
    await page.screenshot({path:path.join(output,'mobile-today.png'),fullPage:true});
    for (let i=0;i<3;i++) await page.locator('.task-row .check-button').nth(i).click();
    assert.equal(await page.locator('.task-row.completed').count(),3);
    await page.locator('#daily-note').fill('今天完成了三件小事。\n慢慢来，也很好。');
    await page.reload();
    assert.equal(await page.locator('.check-button[aria-pressed=true]').count(),3);
    assert.equal(await page.locator('#daily-note').inputValue(),'今天完成了三件小事。\n慢慢来，也很好。');
    await page.locator('.bottom-nav a[href="#tasks"]').click();
    await page.locator('.page-top button[data-action="add-task"]').click();
    await page.locator('#task-title').fill('每天走路 20 分钟 <img src=x>');
    await page.locator('#task-detail').fill('不用很远，出门就算开始。');
    await page.locator('#task-form button[data-action="schedule"][data-days="1,2,3,4,5"]').click();
    await page.locator('#task-form button[type="submit"]').click();
    assert.equal(await page.locator('.managed-task').count(),7);
    await page.locator('.bottom-nav a[href="#today"]').click();
    assert.equal(await page.locator('.task-row').count(),6,'workday task should not show on Sunday');
    await page.locator('.bottom-nav a[href="#tasks"]').click();
    await page.locator('.managed-task').last().locator('[data-action="edit-task"]').click();
    await page.locator('#task-form button[data-action="schedule"][data-days="0,1,2,3,4,5,6"]').click();
    await page.locator('#task-form button[type="submit"]').click();
    await page.locator('.bottom-nav a[href="#today"]').click();
    assert.equal(await page.locator('.task-row').count(),7);
    assert.equal(await page.locator('#main img').count(),0,'user input must be text, not HTML');
    await page.locator('.filter-button[data-filter="todo"]').click();
    assert.equal(await page.locator('.task-row').count(),4);
    await page.locator('.filter-button[data-filter="done"]').click();
    assert.equal(await page.locator('.task-row').count(),3);
    await page.locator('.filter-button[data-filter="all"]').click();
    const pastSnapshot = await page.evaluate(() => {
      const state = JSON.parse(localStorage.getItem('yidian.data.v1'));
      state.days['2026-10-03'] = JSON.parse(JSON.stringify(state.days['2026-10-04']));
      state.days['2026-10-03'].note = '过去的我。';
      localStorage.setItem('yidian.data.v1',JSON.stringify(state));
      return JSON.stringify(state.days['2026-10-03']);
    });
    await page.reload();
    await page.locator('.bottom-nav a[href="#tasks"]').click();
    await page.locator('.managed-task').first().locator('[data-action="edit-task"]').click();
    await page.locator('#task-title').fill('改成新名称');
    await page.locator('#task-form button[type="submit"]').click();
    await page.locator('.managed-task').last().locator('[data-action="move-task"][data-direction="-1"]').click();
    await page.locator('.managed-task').last().locator('[data-action="toggle-task"]').click();
    await page.locator('.managed-task').last().locator('[data-action="toggle-task"]').click();
    await page.locator('.managed-task').last().locator('[data-action="delete-task"]').click();
    await page.locator('#confirm-submit').click();
    assert.equal(await page.locator('.managed-task').count(),6);
    assert.equal(await page.evaluate(() => JSON.stringify(JSON.parse(localStorage.getItem('yidian.data.v1')).days['2026-10-03'])),pastSnapshot);
    await page.locator('.bottom-nav a[href="#settings"]').click();
    await page.locator('#setting-name').fill('慢慢');
    await page.locator('#setting-goal').fill('2');
    await page.locator('#settings-form button[type="submit"]').click();
    assert.equal(await page.evaluate(() => JSON.parse(localStorage.getItem('yidian.data.v1')).settings.goal),2);
    assert.equal(await page.evaluate(() => JSON.parse(localStorage.getItem('yidian.data.v1')).days['2026-10-03'].goal),3);
    const downloadPromise = page.waitForEvent('download');
    await page.locator('[data-action="export"]').click();
    const download = await downloadPromise; const backupPath = path.join(output,'backup.json'); await download.saveAs(backupPath);
    const backup = JSON.parse(fs.readFileSync(backupPath,'utf8')); assert.equal(backup.tasks.length,6);
    await page.locator('#import-file').setInputFiles(backupPath); await page.locator('#confirm-submit').click();
    assert.equal(await page.evaluate(() => JSON.parse(localStorage.getItem('yidian.data.v1')).settings.name),'慢慢');
    const currentData = await page.evaluate(() => localStorage.getItem('yidian.data.v1'));
    await page.locator('#import-file').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{"version":99}')});
    await page.waitForTimeout(100);
    assert.equal(await page.evaluate(() => localStorage.getItem('yidian.data.v1')),currentData);
    await page.locator('.bottom-nav a[href="#history"]').click();
    await page.screenshot({path:path.join(output,'mobile-history.png'),fullPage:true});
    await page.locator('[data-action="select-history"][data-date="2026-10-03"]').click();
    assert.equal(await page.locator('.history-note').textContent(),'过去的我。');
    await page.locator('[data-action="open-day"]').click();
    assert.equal(await page.locator('#day-picker').inputValue(),'2026-10-03');
    await page.locator('[data-action="back-today"]').click();
    assert.equal(await page.locator('#day-picker').inputValue(),'2026-10-04');
    // Device-sized pages must not scroll horizontally on any primary screen.
    for (const width of [320,360,390,430,768]) {
      await page.setViewportSize({width,height:844});
      for (const tab of ['today','history','tasks','settings']) {
        await page.goto(`${baseURL}/#${tab}`);
        const sizes = await page.evaluate(() => ({scroll:document.documentElement.scrollWidth,width:innerWidth}));
        assert.ok(sizes.scroll <= sizes.width,`${tab} overflow at ${width}: ${sizes.scroll}`);
      }
    }
    await page.setViewportSize({width:1440,height:1000});
    await page.goto(baseURL + '/#today');
    await page.screenshot({path:path.join(output,'desktop-today.png'),fullPage:true});
    // Wait until the first page is controlled, then verify a fresh navigation offline.
    await page.evaluate(async () => { await navigator.serviceWorker.ready; if (!navigator.serviceWorker.controller) await new Promise(resolve => navigator.serviceWorker.addEventListener('controllerchange',resolve,{once:true})); });
    await context.setOffline(true);
    await page.reload();
    await page.locator('.task-row').first().waitFor();
    const before = await page.locator('.check-button[aria-pressed=true]').count();
    await page.locator('.task-row .check-button').first().click();
    assert.equal(await page.locator('.check-button[aria-pressed=true]').count(),before-1);
    await page.reload();
    assert.equal(await page.locator('.check-button[aria-pressed=true]').count(),before-1);
    await context.setOffline(false);
    const pastBeforeMidnight = await page.evaluate(() => JSON.stringify(JSON.parse(localStorage.getItem('yidian.data.v1')).days['2026-10-04']));
    await page.clock.setSystemTime(new Date('2026-10-05T03:00:00Z'));
    await page.clock.fastForward(30001);
    assert.equal(await page.locator('#day-picker').inputValue(),'2026-10-05');
    assert.equal(await page.locator('.check-button[aria-pressed=true]').count(),0);
    assert.equal(await page.evaluate(() => JSON.stringify(JSON.parse(localStorage.getItem('yidian.data.v1')).days['2026-10-04'])),pastBeforeMidnight);
    const secondPage = await context.newPage();
    await secondPage.clock.install({time:new Date('2026-10-05T03:00:00Z')});
    await secondPage.goto(baseURL);
    await secondPage.locator('.check-button').first().click();
    await page.locator('.check-button[aria-pressed=true]').first().waitFor();
    assert.equal(await page.locator('.check-button[aria-pressed=true]').count(),1);
    await secondPage.close();
    assert.equal((await page.request.get(`${baseURL}/README.md`)).status(),404);
    assert.deepEqual(errors,[],'no browser exceptions');
    const blockedContext = await browser.newContext();
    await blockedContext.addInitScript(() => { Storage.prototype.setItem = function () { throw new DOMException('Full','QuotaExceededError'); }; });
    const blockedPage = await blockedContext.newPage(); await blockedPage.goto(baseURL);
    assert.equal(await blockedPage.locator('#storage-warning').isVisible(),true);
    await blockedPage.locator('.check-button').first().click();
    assert.equal(await blockedPage.locator('.check-button[aria-pressed=true]').count(),1,'failed storage must retain in-memory work');
    await blockedContext.close();
    const corruptContext = await browser.newContext();
    await corruptContext.addInitScript(() => { localStorage.setItem('yidian.data.v1','corrupt-original'); });
    const corruptPage = await corruptContext.newPage(); await corruptPage.goto(baseURL);
    await corruptPage.locator('.check-button').first().click();
    assert.equal(await corruptPage.evaluate(() => localStorage.getItem('yidian.data.v1')),'corrupt-original','unreadable original must not be overwritten');
    await corruptContext.close();
    console.log('PASS: mobile CRUD, schedules, persistence, filters, historical snapshots, goals, backup round-trip, invalid imports, 20 responsive layouts, offline saving, midnight reset, cross-tab sync, storage failure recovery, corrupt-data protection, server resource boundary.');
    await context.close();
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
